DROP TABLE IF EXISTS score;

CREATE TABLE score (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  playerName INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  score INTEGER NOT NULL
);